openapi: 3.0.0
info:
  title: Azure OpenAI API
  description: The Azure OpenAI REST API
  version: 1.0.0
servers:
  - url: https://{resource-name}.openai.azure.com/openai/deployments/{deployment-name}
paths:
  /chat/completions:
    post:
      summary: Creates a model response for the given chat conversation.
      operationId: createChatCompletion
      parameters:
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChatCompletionRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChatCompletionResponse'
components:
  schemas:
    CreateChatCompletionRequest:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ChatCompletionRequestMessage'
    CreateChatCompletionResponse:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
        created:
          type: integer
        model:
          type: string
        choices:
          type: array
          items:
            $ref: '#/components/schemas/ChatCompletionResponseChoice'
    ChatCompletionRequestMessage:
      type: object
      properties:
        role:
          type: string
          enum: [system, user, assistant]
        content:
          type: string
    ChatCompletionResponseChoice:
      type: object
      properties:
        index:
          type: integer
        message:
          $ref: '#/components/schemas/ChatCompletionRequestMessage'
        finish_reason:
          type: string